# Generated by Django 5.2.6 on 2025-10-09 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicleinterest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='AI-generated conversation summary')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('use_case', models.CharField(blank=True, max_length=255, null=True)),
                ('priority_features', models.JSONField(default=list, help_text='List of important features')),
                ('recommended_vehicles', models.JSONField(default=list, help_text='Vehicles recommended during conversation')),
                ('next_actions', models.JSONField(default=list, help_text='Suggested follow-up actions')),
                ('sentiment', models.CharField(blank=True, help_text='Overall sentiment: positive/neutral/negative', max_length=50, null=True)),
                ('engagement_score', models.IntegerField(default=5, help_text='1-10 scale')),
                ('purchase_intent', models.CharField(blank=True, help_text='high/medium/low', max_length=50, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='assistant.conversation')),
            ],
            options={
                'verbose_name_plural': 'Conversation Summaries',
                'ordering': ['-generated_at'],
            },
        ),
    ]
