# Generated by Django 4.2.25 on 2025-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
