# Generated by Django 4.2.25 on 2025-10-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_conversation_summary_emailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='summary_emailed',
        ),
    ]
