# Generated by Django 4.2.25 on 2025-10-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_conversation_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages_json',
            field=models.JSONField(default=list, help_text="List of messages: [{'role':'user'/'assistant', 'content':..., 'timestamp':...}]"),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
