# Generated by Django 4.2.25 on 2025-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_remove_conversation_summary_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
