# Generated by Django 4.2.25 on 2025-10-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_conversation_messages_json_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ['-extracted_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicleinterest',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='engagement_score',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='next_actions',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='priority_features',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='purchase_intent',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='recommended_vehicles',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='summary_text',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='use_case',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='features_matched',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preference_type',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='value',
        ),
        migrations.RemoveField(
            model_name='vehicleinterest',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='vehicleinterest',
            name='mentioned_features',
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='data',
            field=models.JSONField(default=dict, help_text='Store all summary and details in a single JSON object.'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='data',
            field=models.JSONField(default=dict, help_text="e.g. {'vehicle_name': ..., 'reason': ..., 'score': ..., 'features': [...]}"),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='data',
            field=models.JSONField(default=dict, help_text="e.g. {'type': 'budget', 'value': '10-15 lakhs', 'confidence': 0.8}"),
        ),
        migrations.AddField(
            model_name='vehicleinterest',
            name='meta',
            field=models.JSONField(default=dict, help_text="e.g. {'interest_level': 5, 'features': [...]} (optional)"),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages_json',
            field=models.JSONField(default=list, help_text='List of messages as dicts'),
        ),
    ]
